default: &default
  host: localhost
  adapter: postgresql
  username: postgres
  password: 123456

development:
  <<: *default
  database: simapro_development

test:
  <<: *default
  database: simapro_test
#
production:
  <<: *default
  database: simapro_production
